#!/bin/bash
# =============================================================================
# config.sh - Configuration constants and YAML generation
# =============================================================================

# Default configuration
DEFAULT_INSTALL_DIR="$HOME/.power-node"
DEFAULT_API_URL="https://api.gelotto.io"
HF_BASE="https://huggingface.co"
GITHUB_REPO="Gelotto/power-node"

# Disk space requirements (GB)
declare -A DISK_REQUIREMENTS=(
    [zimage-gguf]=12
    [zimage-pytorch]=35
    [flux-gguf]=25
    [flux-pytorch]=30
    [video-model]=50
)

# VRAM thresholds for model quantization selection
ZIMAGE_Q4_THRESHOLD=10  # Use Q4_0 below this
FLUX_Q4_THRESHOLD=12    # Use Q4_K_S below this

# Initialize configuration variables
init_config() {
    INSTALL_DIR="${POWER_NODE_DIR:-$DEFAULT_INSTALL_DIR}"
    API_URL="${API_URL:-$DEFAULT_API_URL}"
}

# Create directory structure
create_directories() {
    log_step 4 "Creating directory structure..."

    mkdir -p "$INSTALL_DIR"/{bin,config,logs,scripts,models/{diffusion,vae,text_encoder}}

    log_info "Install directory: ${GREEN}$INSTALL_DIR${NC}"
}

# Generate the main config.yaml file
generate_config() {
    local service_mode="$1"
    local model_name="$2"
    local script_path="$3"
    local script_args="$4"

    cat > "$INSTALL_DIR/config/config.yaml" << EOF
# Power Node Configuration
# Generated by install.sh - $(date)

api:
  url: $API_URL
  key: "\${POWER_NODE_API_KEY}"  # Set via environment variable

worker:
  heartbeat_interval: 30s
  job_timeout: 5m

model:
  name: $model_name
  service_mode: $service_mode

gpu:
  vram_gb: $VRAM_GB
  compute_cap: "${COMPUTE_CAP:0:1}.${COMPUTE_CAP:1}"

python:
  venv_path: $INSTALL_DIR/venv
  script_path: $script_path
  script_args:
    $script_args
EOF
}

# Generate config for GGUF Z-Image mode
generate_gguf_zimage_config() {
    local quant="${1:-Q8_0}"
    local script_args="--diffusion $INSTALL_DIR/models/diffusion/z-image-turbo-${quant}.gguf
    --vae $INSTALL_DIR/models/vae/sdxl_vae.safetensors
    --text-encoder $INSTALL_DIR/models/text_encoder/Qwen2.5-0.5B-${quant}.gguf
    --vram $VRAM_GB"

    generate_config "gguf" "z-image-turbo" "$INSTALL_DIR/scripts/inference.py" "$script_args"
}

# Generate config for GGUF FLUX mode
generate_gguf_flux_config() {
    local quant="${1:-Q8_0}"
    local script_args="--diffusion $INSTALL_DIR/models/diffusion/flux1-schnell-${quant}.gguf
    --clip $INSTALL_DIR/models/text_encoder/clip_l.safetensors
    --t5 $INSTALL_DIR/models/text_encoder/t5xxl_fp16.safetensors
    --vae $INSTALL_DIR/models/vae/ae.safetensors
    --vram $VRAM_GB"

    generate_config "gguf" "flux-schnell" "$INSTALL_DIR/scripts/inference.py" "$script_args"
}

# Generate config for PyTorch Z-Image mode
generate_pytorch_zimage_config() {
    local script_args="--model $INSTALL_DIR/models/Z-Image-Turbo"

    generate_config "pytorch" "z-image-turbo" "$INSTALL_DIR/scripts/inference.py" "$script_args"
}

# Generate config for PyTorch FLUX mode
generate_pytorch_flux_config() {
    local script_args="--model $INSTALL_DIR/models/FLUX.1-schnell"

    generate_config "pytorch" "flux-schnell" "$INSTALL_DIR/scripts/inference.py" "$script_args"
}

# Append video configuration
append_video_config() {
    local wan_model_path="$1"

    cat >> "$INSTALL_DIR/config/config.yaml" << EOF

video:
  enabled: true
  model_path: $wan_model_path
EOF
}

# Append multi-model configuration
append_multimodel_config() {
    local zimage_script="$1"
    local flux_script="$2"

    cat >> "$INSTALL_DIR/config/config.yaml" << EOF

models:
  z-image-turbo:
    script_path: $zimage_script
    priority: 1
  flux-schnell:
    script_path: $flux_script
    priority: 2
EOF
}

# Append face-swap configuration
append_faceswap_config() {
    local model_path="$1"

    cat >> "$INSTALL_DIR/config/config.yaml" << EOF

faceswap:
  enabled: true
  model_path: $model_path
EOF
}

# Generate start script
generate_start_script() {
    cat > "$INSTALL_DIR/start.sh" << 'EOF'
#!/bin/bash
cd "$(dirname "$0")"
./bin/power-node --config config/config.yaml
EOF
    chmod +x "$INSTALL_DIR/start.sh"
}

# Generate systemd service file
generate_systemd_service() {
    local user=$(whoami)

    cat > "$INSTALL_DIR/power-node.service" << EOF
[Unit]
Description=Power Node Worker
After=network.target

[Service]
Type=simple
User=$user
WorkingDirectory=$INSTALL_DIR
ExecStart=$INSTALL_DIR/bin/power-node --config $INSTALL_DIR/config/config.yaml
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
}

# Generate update script
generate_update_script() {
    cat > "$INSTALL_DIR/update.sh" << 'UPDATEEOF'
#!/bin/bash
set -e

INSTALL_DIR="$(dirname "$0")"
GITHUB_REPO="Gelotto/power-node"

ARCH=$(uname -m)
OS=$(uname -s | tr '[:upper:]' '[:lower:]')

if [ "$ARCH" = "aarch64" ]; then
    ARCH="arm64"
fi

BINARY_URL="https://github.com/$GITHUB_REPO/releases/latest/download/power-node-${OS}-${ARCH}"

echo "Downloading latest Power Node binary..."
if curl -fsSL "$BINARY_URL" -o "$INSTALL_DIR/bin/power-node.new"; then
    chmod +x "$INSTALL_DIR/bin/power-node.new"
    mv "$INSTALL_DIR/bin/power-node.new" "$INSTALL_DIR/bin/power-node"
    echo "Update complete!"
else
    echo "Failed to download update"
    rm -f "$INSTALL_DIR/bin/power-node.new"
    exit 1
fi
UPDATEEOF
    chmod +x "$INSTALL_DIR/update.sh"
}
