#!/bin/bash
# =============================================================================
# config.sh - Configuration constants and YAML generation
# =============================================================================

# Default configuration
DEFAULT_INSTALL_DIR="$HOME/.power-node"
DEFAULT_API_URL="https://api.gelotto.io"
HF_BASE="https://huggingface.co"
GITHUB_REPO="Gelotto/power-node"

# Disk space requirements (GB)
declare -A DISK_REQUIREMENTS=(
    [zimage-gguf]=12
    [zimage-pytorch]=35
    [flux-gguf]=25
    [flux-pytorch]=30
    [video-model]=50
)

# VRAM thresholds for model quantization selection
ZIMAGE_Q4_THRESHOLD=10  # Use Q4_0 below this
FLUX_Q4_THRESHOLD=12    # Use Q4_K_S below this

# Initialize configuration variables
init_config() {
    INSTALL_DIR="${POWER_NODE_DIR:-$DEFAULT_INSTALL_DIR}"
    API_URL="${API_URL:-$DEFAULT_API_URL}"
}

# Create directory structure
create_directories() {
    log_step 4 "Creating directory structure..."

    mkdir -p "$INSTALL_DIR"/{bin,config,logs,scripts,models/{diffusion,vae,text_encoder}}

    log_info "Install directory: ${GREEN}$INSTALL_DIR${NC}"
}

# Generate the main config.yaml file
generate_config() {
    local service_mode="$1"
    local model_name="$2"
    local script_path="$3"
    shift 3
    local script_args=("$@")  # Remaining args as array

    # Preserve existing credentials if config exists
    local existing_api_key=""
    local existing_worker_id=""
    if [ -f "$INSTALL_DIR/config/config.yaml" ]; then
        existing_api_key=$(grep -E "^\s*key:" "$INSTALL_DIR/config/config.yaml" | head -1 | sed 's/.*key:\s*//' | tr -d '"' | tr -d "'" | xargs)
        existing_worker_id=$(grep -E "^\s*id:" "$INSTALL_DIR/config/config.yaml" | head -1 | sed 's/.*id:\s*//' | tr -d '"' | tr -d "'" | xargs)
    fi

    # Use existing key or placeholder (skip placeholder-like values)
    local api_key="\${POWER_NODE_API_KEY}"
    if [ -n "$existing_api_key" ] && [[ "$existing_api_key" == wk_* ]]; then
        api_key="$existing_api_key"
    fi

    # Build worker section with optional id
    local worker_id_line=""
    if [ -n "$existing_worker_id" ] && [[ "$existing_worker_id" =~ ^[0-9a-f-]{36}$ ]]; then
        worker_id_line=$'\n  id: '"$existing_worker_id"
    fi

    cat > "$INSTALL_DIR/config/config.yaml" << EOF
# Power Node Configuration
# Generated by install.sh - $(date)

api:
  url: $API_URL
  key: "$api_key"

worker:${worker_id_line}
  heartbeat_interval: 30s
  job_timeout: 5m

model:
  name: $model_name
  service_mode: $service_mode

gpu:
  vram_gb: $VRAM_GB
  compute_cap: "${COMPUTE_CAP:0:1}.${COMPUTE_CAP:1}"

python:
  venv_path: $INSTALL_DIR/venv
  script_path: $script_path
  script_args:
EOF

    # Append script_args as proper YAML array
    for arg in "${script_args[@]}"; do
        echo "    - \"$arg\"" >> "$INSTALL_DIR/config/config.yaml"
    done
}

# Generate config for GGUF Z-Image mode
generate_gguf_zimage_config() {
    local quant="${1:-Q8_0}"
    generate_config "gguf" "z-image-turbo" "$INSTALL_DIR/scripts/inference.py" \
        "--diffusion" "$INSTALL_DIR/models/diffusion/z-image-turbo-${quant}.gguf" \
        "--vae" "$INSTALL_DIR/models/vae/sdxl_vae.safetensors" \
        "--text-encoder" "$INSTALL_DIR/models/text_encoder/Qwen2.5-0.5B-${quant}.gguf" \
        "--vram" "$VRAM_GB"
}

# Generate config for GGUF FLUX mode
generate_gguf_flux_config() {
    local quant="${1:-Q8_0}"
    generate_config "gguf" "flux-schnell" "$INSTALL_DIR/scripts/inference.py" \
        "--diffusion" "$INSTALL_DIR/models/diffusion/flux1-schnell-${quant}.gguf" \
        "--clip" "$INSTALL_DIR/models/text_encoder/clip_l.safetensors" \
        "--t5" "$INSTALL_DIR/models/text_encoder/t5xxl_fp16.safetensors" \
        "--vae" "$INSTALL_DIR/models/vae/ae.safetensors" \
        "--vram" "$VRAM_GB"
}

# Generate config for PyTorch Z-Image mode
generate_pytorch_zimage_config() {
    generate_config "pytorch" "z-image-turbo" "$INSTALL_DIR/scripts/inference.py" \
        "--model" "$INSTALL_DIR/models/Z-Image-Turbo"
}

# Generate config for PyTorch FLUX mode
generate_pytorch_flux_config() {
    generate_config "pytorch" "flux-schnell" "$INSTALL_DIR/scripts/inference.py" \
        "--model" "$INSTALL_DIR/models/FLUX.1-schnell"
}

# Append video configuration
append_video_config() {
    local wan_model_path="$1"

    cat >> "$INSTALL_DIR/config/config.yaml" << EOF

video:
  enabled: true
  model_path: $wan_model_path
EOF
}

# Append multi-model configuration
append_multimodel_config() {
    local zimage_path="$1"
    local flux_path="$2"

    cat >> "$INSTALL_DIR/config/config.yaml" << EOF

models:
  idle_timeout: 5m
  models:
    - name: z-image-turbo
      path: $zimage_path
      priority: 0
    - name: flux-schnell
      path: $flux_path
      priority: 1
EOF
}

# Append face-swap configuration
append_faceswap_config() {
    local model_path="$1"

    cat >> "$INSTALL_DIR/config/config.yaml" << EOF

faceswap:
  enabled: true
  model_path: $model_path
EOF
}

# Generate start script
generate_start_script() {
    cat > "$INSTALL_DIR/start.sh" << 'EOF'
#!/bin/bash
cd "$(dirname "$0")"
./bin/power-node --config config/config.yaml
EOF
    chmod +x "$INSTALL_DIR/start.sh"
}

# Generate systemd service file
generate_systemd_service() {
    local user=$(whoami)

    cat > "$INSTALL_DIR/power-node.service" << EOF
[Unit]
Description=Power Node Worker
After=network.target

[Service]
Type=simple
User=$user
WorkingDirectory=$INSTALL_DIR
ExecStart=$INSTALL_DIR/bin/power-node --config $INSTALL_DIR/config/config.yaml
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
}

# Generate update script
generate_update_script() {
    cat > "$INSTALL_DIR/update.sh" << 'UPDATEEOF'
#!/bin/bash
set -e

INSTALL_DIR="$(dirname "$0")"
GITHUB_REPO="Gelotto/power-node"

ARCH=$(uname -m)
OS=$(uname -s | tr '[:upper:]' '[:lower:]')

if [ "$ARCH" = "aarch64" ]; then
    ARCH="arm64"
fi

BINARY_URL="https://github.com/$GITHUB_REPO/releases/latest/download/power-node-${OS}-${ARCH}"

echo "Downloading latest Power Node binary..."
if curl -fsSL "$BINARY_URL" -o "$INSTALL_DIR/bin/power-node.new"; then
    chmod +x "$INSTALL_DIR/bin/power-node.new"
    mv "$INSTALL_DIR/bin/power-node.new" "$INSTALL_DIR/bin/power-node"
    echo "Update complete!"
else
    echo "Failed to download update"
    rm -f "$INSTALL_DIR/bin/power-node.new"
    exit 1
fi
UPDATEEOF
    chmod +x "$INSTALL_DIR/update.sh"
}
